### ISSUE TITLE
An inquiry of NYC data

### ISSUE THREAD

**Issue by MinNamgung** [LightChaser666/RegionDCL#1]
Hi,

Thanks for such a great work! i'd like to test this code with NYC dataset. When do you plan to offer the preprocessed data and groundtruth?

**Comment by Rajjat** [comment]
Hello Authors,
I have a similar question.  Could you please share the preprocessed data for  NYC?
Thanks.

**Comment by pkuliyi2015** [comment]
I'm sorry for late reply. Here I provided the raw & projected dataset of both NYC and Singapore in 7zip form. The preprocess.py can turn them into processed data automatically, but you may need to use the resnet.py to convert the rasterized buildings into resnet features on your own (warning: that feature will be huge as NYC has too many buildings).

If any problems, please feel free to reply here or via email!

**Comment by pkuliyi2015** [comment]
Please figure out if any data is missing. I will close this issue now.
